package com.workspace.crm.settings.mapper;

import com.workspace.crm.settings.pojo.DictionaryType;

import java.util.List;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jan 08 17:48:08 JST 2024
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jan 08 17:48:08 JST 2024
     */
    int insert(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jan 08 17:48:08 JST 2024
     */
    int insertSelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jan 08 17:48:08 JST 2024
     */
    DictionaryType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jan 08 17:48:08 JST 2024
     */
    int updateByPrimaryKeySelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Jan 08 17:48:08 JST 2024
     */
    int updateByPrimaryKey(DictionaryType record);

    //查询所有的数据字典类型
    List<DictionaryType> selectAllDicTypeByPages(int beginNo,int pageSize);

    //保存新增的字典数据类型
    int insertDicType(DictionaryType type);

    //批量删除字典数据类型
    int deleteDicTypeByCode(String[] codeArray);

    //根据code修改字典数据类型
    int updateDicTypeByCode(DictionaryType type);

    //根据code查询单个字典数据类型
    DictionaryType selectDicTypeByCode(String code);


    List<DictionaryType> selectAllTypes();
}