package com.workspace.crm.settings.mapper;

import com.workspace.crm.settings.pojo.DictionaryType;
import com.workspace.crm.settings.pojo.DictionaryValue;

import java.util.List;
import java.util.Map;

public interface DictionaryValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Jan 10 20:09:48 JST 2024
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Jan 10 20:09:48 JST 2024
     */
    int insert(DictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Jan 10 20:09:48 JST 2024
     */
    int insertSelective(DictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Jan 10 20:09:48 JST 2024
     */
    DictionaryValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Jan 10 20:09:48 JST 2024
     */
    int updateByPrimaryKeySelective(DictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Jan 10 20:09:48 JST 2024
     */
    int updateByPrimaryKey(DictionaryValue record);

    //查询所有的值
    List<DictionaryValue> selectAllValueByPage(Map<String,Object> map);

    //查询记录条数
    int selectCountOfValues();

    //删除数据
    int deleteByIds(String[] id);

    //更改数据
    int updateById(DictionaryValue value);

    //添加数据
    int insertData(DictionaryValue value);

    DictionaryValue selectValueById(String id);


    List<DictionaryValue> selectValueByType(String type);
}